{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "scanner.serviceAccountName" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "scanner.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
{{ end }}
