apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: scanner
  namespace: ${SCANNER_NAMESPACE}
  labels:
    app: scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      labels:
        app: scanner
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: ${SCANNER_SERVICE_ACCOUNT}
      imagePullSecrets: [${SCANNER_IMAGE_PULL_SECRET}]
      containers:
      - name: operator
        args:
        - run
        - --v=3
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --enable-analytics=${SCANNER_ENABLE_ANALYTICS}
        image: ${SCANNER_DOCKER_REGISTRY}/scanner:remove
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: scanner-apiserver-cert
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
---
# kube lacks the service serving cert signer, so provide a manual secret for it
apiVersion: v1
kind: Secret
metadata:
  name: scanner-apiserver-cert
  namespace: ${SCANNER_NAMESPACE}
  labels:
    app: scanner
type: kubernetes.io/tls
data:
  tls.crt: ${TLS_SERVING_CERT}
  tls.key: ${TLS_SERVING_KEY}
---
# to be able to expose TSB inside the cluster
apiVersion: v1
kind: Service
metadata:
  name: scanner
  namespace: ${SCANNER_NAMESPACE}
  labels:
    app: scanner
spec:
  ports:
  - name: api
    port: 443
    targetPort: 8443
  selector:
    app: scanner
---
# register as aggregated apiserver
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.scanner.soter.cloud
  labels:
    app: scanner
spec:
  caBundle: ${SERVICE_SERVING_CERT_CA}
  group: scanner.soter.cloud
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: scanner
    namespace: ${SCANNER_NAMESPACE}
  version: v1alpha1
