apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "scanner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "scanner.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ template "scanner.name" . }}"
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ template "scanner.name" . }}"
        release: "{{ .Release.Name }}"
{{- if and .Values.criticalAddon (eq .Release.Namespace "kube-system") }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
{{- end }}
    spec:
      serviceAccountName: {{ template "scanner.serviceAccountName" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
      {{- end }}
      containers:
      - name: scanner
        image: {{ .Values.scanner.registry }}/{{ .Values.scanner.repository }}:{{ .Values.scanner.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - run
        - --v={{ .Values.logLevel }}
        - --rbac={{ .Values.rbac.create }}
        - --docker-registry={{ .Values.scanner.registry }}
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --enable-analytics={{ .Values.enableAnalytics }}
        ports:
        - containerPort: 8443
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ template "scanner.fullname" . }}-apiserver-cert
{{- if and .Values.criticalAddon (eq .Release.Namespace "kube-system") }}
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end -}}
