apiVersion: v1
kind: Secret
metadata:
  name: scanner-notifier-cert
  namespace: ${SCANNER_NAMESPACE}
  labels:
    app: clair
data:
  ca.crt: ${SERVICE_SERVING_CERT_CA}
  client.crt: ${NOTIFIER_CLIENT_CERT}
  client.key: ${NOTIFIER_CLIENT_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: clair-server-cert
  namespace: ${SCANNER_NAMESPACE}
  labels:
    app: clair
data:
  ca.crt: ${CLAIR_API_SERVING_CERT_CA}
  server.crt: ${CLAIR_API_SERVER_CERT}
  server.key: ${CLAIR_API_SERVER_KEY}
---
apiVersion: v1
kind: Service
metadata:
  name: clairsvc
  namespace: ${SCANNER_NAMESPACE}
  labels:
    app: clair
spec:
  type: NodePort
  ports:
  - port: 6060
    protocol: TCP
    nodePort: 30060
    name: clair-port0
  - port: 6061
    protocol: TCP
    nodePort: 30061
    name: clair-port1
  selector:
    app: clair
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clair
  namespace: ${SCANNER_NAMESPACE}
  labels:
    app: clair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clair
  template:
    metadata:
      labels:
        app: clair
    spec:
      containers:
      - name: clair
        image: quay.io/coreos/clair-git:latest
        imagePullPolicy: Always
        args:
        - "-config"
        - "/etc/clair/config.yaml"
        - -log-level=info
        livenessProbe:
          httpGet:
            path: /health
            port: 6061
        ports:
        - containerPort: 6060
          name: clair-api
        - containerPort: 6061
          name: clair-health
        readinessProbe:
          httpGet:
            path: /health
            port: 6061
        volumeMounts:
        - mountPath: /etc/clair
          name: clair-config
        - mountPath: /var/run/secrets/clair
          name: clair-server-cert
          readOnly: true
        - mountPath: /var/run/secrets/scanner
          name: scanner-notifier-cert
          readOnly: true
      volumes:
      - name: clair-config
        configMap:
          name: clair-config
      - name: clair-server-cert
        secret:
          secretName: clair-server-cert
      - name: scanner-notifier-cert
        secret:
          secretName: scanner-notifier-cert
