apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "clair.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "clair.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "clair.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "clair.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - "-log-level={{ .Values.logLevel }}"
        {{ if .Values.insecureTls }}- "--insecure-tls" {{end}}
        ports:
        - name: clair-api
          containerPort: {{ .Values.service.internalApiPort }}
          protocol: TCP
        - name: clair-health
          containerPort: {{ .Values.service.internalHealthPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.internalHealthPort }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.internalHealthPort }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - mountPath: /etc/clair
          name: clair-config
        - mountPath: /var/run/secrets/clair
          name: clair-server-cert
          readOnly: true
{{- if .Values.scanner.enabled }}
        - mountPath: /var/run/secrets/scanner
          name: clair-notifier-cert
          readOnly: true
{{- end }}
      volumes:
      - name: clair-config
        configMap:
          name: {{ template "clair.fullname" . }}
      - name: clair-server-cert
        secret:
          secretName: {{ template "clair.fullname" . }}-server-cert
{{- if .Values.scanner.enabled }}
      - name: clair-notifier-cert
        secret:
          secretName: {{ template "scanner.release" . }}-notifier-cert
{{- end }}
